import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

import { Separator } from "@/components/ui/separator";

import Header from "@/components/sections/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-[100dvh] flex flex-col`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <Separator />
          <main className="flex flex-col flex-grow justify-center w-10/12 xl:max-w-screen-lg mx-auto">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
